FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN meltano install
# entrpoint.sh faz o unzip dos csvs no container para 'data/csvs'
COPY entrypoint.sh /entrypoint.sh   
RUN chmod +x /entrypoint.sh

ENV BANVIC_DATA_DIR=/data/banvic_data

ENTRYPOINT ["/entrypoint.sh"] 

CMD ["run", "tap-csv", "target-s3"]